behaviors:
  PaddleTest:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 256
          num_layers: 2
    max_steps: 2500000
    time_horizon: 1000
    summary_freq: 20000